name: waryan

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    # WAJIB: Izin agar GitHub bisa menjalankan ulang workflow otomatis
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run bot
        run: python -u bot.py # Pastikan file Python kamu namanya bot.py

      - name: Re-run Workflow Automatically
        if: always() # Tetap jalankan rerun meski skrip sukses atau ada error
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list --workflow "Febspot Bot Manual Mode" --status completed --limit 100 --json databaseId | jq -r '.[].databaseId' | xargs -I{} gh run delete {} || true
          echo "Menunggu 1 menit agar sistem tidak overload..."
          sleep 60
          gh workflow run "Febspot Bot Manual Mode"
